/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HomePromo: typeof import('./src/components/HomeSections/HomePromo.vue')['default']
    MovieAbout: typeof import('./src/components/MovieSections/MovieAbout.vue')['default']
    MovieActors: typeof import('./src/components/MovieSections/MovieActors.vue')['default']
    MovieAwards: typeof import('./src/components/MovieSections/MovieAwards.vue')['default']
    MovieFacts: typeof import('./src/components/MovieSections/MovieFacts.vue')['default']
    MovieFrames: typeof import('./src/components/MovieSections/MovieFrames.vue')['default']
    MoviePlatforms: typeof import('./src/components/MovieSections/MoviePlatforms.vue')['default']
    MoviePlayer: typeof import('./src/components/Movie/MoviePlayer.vue')['default']
    MoviePromo: typeof import('./src/components/MovieSections/MoviePromo.vue')['default']
    MovieRewards: typeof import('./src/components/MovieSections/MovieRewards.vue')['default']
    MovieSource: typeof import('./src/components/Movie/MovieSource.vue')['default']
    Promo: typeof import('./src/components/Promo/Promo.vue')['default']
    PromoComponent: typeof import('./src/components/Promo/PromoComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
