/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HeaderComponent: typeof import('./src/components/Header/HeaderComponent.vue')['default']
    Promo: typeof import('./src/components/Promo/Promo.vue')['default']
    PromoComponent: typeof import('./src/components/Promo/PromoComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
